
jobs:

# ------------------------------------------------------------------------------------------------------
# Request latest Ubunto/Linux
# ------------------------------------------------------------------------------------------------------
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

# ------------------------------------------------------------------------------------------------------
# Job Variables
# ------------------------------------------------------------------------------------------------------
  variables:  
    solution: '**/*.sln'     # = /home/vsts/work/1/s/Ginger
    buildConfiguration: 'Release'     
    # artifactsFolder: 'D:\a\1\a' 
  
  steps:
  
  - script: dotnet test  Ginger/GingerUtilsTest --configuration $(buildConfiguration) --logger trx --verbosity=normal
    displayName: 'Testing GingerUtilsTest'

  - script: dotnet test  Ginger/GingerCoreCommonTest --configuration $(buildConfiguration) --logger trx --verbosity=normal
    displayName: 'Testing GingerCoreCommonTest'

    # for GingerCoreNET we use run setting to limit to have one worker thread due to workspace limitation
  - script: dotnet test  Ginger/GingerCoreNETUnitTest --configuration $(buildConfiguration) --logger trx --verbosity=normal
    displayName: 'Testing GingerCoreNETUnitTest'

  - script: dotnet test  Ginger/GingerPluginCoreTest --configuration $(buildConfiguration) --logger trx --verbosity=normal
    displayName: 'Testing GingerPluginCoreTest'

  - script: dotnet test  Ginger/GingerConsoleTest --configuration $(buildConfiguration) --logger trx --verbosity=normal
    displayName: 'Testing GingerConsoleTest'

  - script: dotnet test  Ginger/GingerAutoPilotTest --configuration $(buildConfiguration) --logger trx --verbosity=normal
    displayName: 'Testing GingerAutoPilotTest'

# ------------------------------------------------------------------------------------------------------
# Publish GingerConsole
# ------------------------------------------------------------------------------------------------------

  - script: dotnet publish  Ginger/GingerConsole -c Release
    displayName: 'Publish GingerConsole'
    
# ------------------------------------------------------------------------------------------------------
# Publish Test Results
# ------------------------------------------------------------------------------------------------------

  - task: PublishTestResults@2
    displayName: Publish test result
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

# ------------------------------------------------------------------------------------------------------
# Run Standalone CLI Test
# ------------------------------------------------------------------------------------------------------

  - task: PowerShell@2
    displayName: Run Standalone CLI Test
    inputs:
      filePath: CLITests.ps1
    condition: succeededOrFailed()


# ------------------------------------------------------------------------------------------------------
# Package Test Artifacts
# ------------------------------------------------------------------------------------------------------

  - task: PowerShell@2
    displayName: Package test artifacts
    inputs:
      filePath: PackageTestArtifacts.ps1
    condition: succeededOrFailed()



# ------------------------------------------------------------------------------------------------------
# Publish Test Artifacts
# ------------------------------------------------------------------------------------------------------

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
