
# .NET

jobs:

# ------------------------------------------------------------------------------------------------------
# Request Linux Ubunto 16.04 VM 
# ------------------------------------------------------------------------------------------------------
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'

# ------------------------------------------------------------------------------------------------------
# Job Variables
# ------------------------------------------------------------------------------------------------------
  variables:  
    solution: '**/*.sln'     # = /home/vsts/work/1/s/Ginger
    buildConfiguration: 'Release'     
    # artifactsFolder: 'D:\a\1\a' 
  
  steps:
  
# ------------------------------------------------------------------------------------------------------
# Install Nuget tool
# ------------------------------------------------------------------------------------------------------
  #- task: NuGetToolInstaller@0  
  #  displayName: NuGet Tool Installer

# ------------------------------------------------------------------------------------------------------
# Restore Ginger solution NuGet packages
# ------------------------------------------------------------------------------------------------------
  #- task: NuGetCommand@2
  #  inputs:
  #    command: restore  
  #    restoreSolution: '$(**\GingerCoreCommonTest\GingerCoreCommonTest.csproj **\GingerCoreNetTest\GingerCoreNetTest.csproj)'       
  #  displayName: Restore Ginger .net core projects Nuget Packages
  
# ------------------------------------------------------------------------------------------------------
# Build Ginger DLLs .Net Core only
# ------------------------------------------------------------------------------------------------------

  #- script: dotnet build '$(**\GingerCoreCommonTest\GingerCoreCommonTest.csproj)'
  #  displayName: Build Ginger DLLs

# ------------------------------------------------------------------------------------------------------
# Run Unit Test Level 1,2,3 for .NET Core testDLLs
# ------------------------------------------------------------------------------------------------------
    
    # TODO: run unit test by level 1,2,3 continue on success only

  #- task: DotNetCoreCLI@2
  #  displayName: 'Run Unit tests Level for .Net Core test DLLs'
  #  inputs:
  #    command: test
  #    projects: '**/**/*Test.csproj'          # test all csproj, it will skip .Net Framework
  #    arguments: '--configuration $(buildConfiguration)'   # not working on Linux !?  --collect "Code coverage"

  

  - script: dotnet test  Ginger/GingerCoreCommonTest/GingerCoreCommonTest.csproj --configuration $(buildConfiguration) --logger trx
    displayName: 'dotnet test 33333333333'
    

  - script: dotnet test  Ginger/Ginger.sln --configuration $(buildConfiguration) --logger trx
    displayName: 'Run tests on Ginger solution'


    

  - task: PublishTestResults@2
    displayName: Publish test result
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

  #- task: PublishBuildArtifacts@1

  
  #- task: PublishTestResults@2
  #  condition: succeededOrFailed()
  #  inputs:
  #    testRunner: VSTest
  #    testResultsFiles: '**/*.trx'


 # - task: PublishBuildArtifacts@1


 # failTaskOnFailedTests: true

 #- task: PublishBuildArtifacts@1
 # displayName: "Publish artifacts"
 # inputs:
 #   PathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
 #   ArtifactName: app
 #   publishLocation: Container