name: Ginger_Builder

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    
    env:
      BUILD_CONFIGURATION: Release
      
    steps:
      - uses: actions/checkout@v3

# ------------------------------------------------------------------------------------------------------
# Install .Net core SDK 6.0.301
# ------------------------------------------------------------------------------------------------------
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.301
          
# ------------------------------------------------------------------------------------------------------
# Install Nuget tool v1.0.5
# ------------------------------------------------------------------------------------------------------
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1.0.5

# ------------------------------------------------------------------------------------------------------
# Restore Ginger solution NuGet packages
# ------------------------------------------------------------------------------------------------------
      - name: Restore nuget packages
        run: nuget restore ./Ginger/Ginger.sln
        
# ------------------------------------------------------------------------------------------------------
# Install msbild && Build Ginger Solution
# ------------------------------------------------------------------------------------------------------
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Ginger Solution
        run: msbuild ./Ginger/Ginger.sln /p:DebugSymbols=true /p:DebugType=full /p:Configuration=$env:BUILD_CONFIGURATION
        
# ------------------------------------------------------------------------------------------------------
# Upload Artifacts 
# ------------------------------------------------------------------------------------------------------    
      - name: Upload static site content
        uses: actions/upload-artifact@v3
        with:
          name: ginger-artifact

