//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amdocs.Ginger.CoreNET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amdocs.Ginger.CoreNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Copyright © 2014-2020 European Support Limited
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;)
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at 
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0 
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        ///See the License for the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string draganddrop {
            get {
                return ResourceManager.GetString("draganddrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Copyright © 2014-2020 European Support Limited
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;)
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at 
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0 
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        ///See the License for the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GingerHTMLHelper {
            get {
                return ResourceManager.GetString("GingerHTMLHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Copyright © 2014-2020 European Support Limited
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;)
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at 
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0 
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        ///See the License for the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GingerHTMLRecorder {
            get {
                return ResourceManager.GetString("GingerHTMLRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Copyright © 2014-2020 European Support Limited
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;)
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at 
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0 
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        ///See the License for the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GingerLibXPath {
            get {
                return ResourceManager.GetString("GingerLibXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Copyright © 2014-2020 European Support Limited
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;)
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at 
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0 
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        ///See the License for the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GingerLiveSpy {
            get {
                return ResourceManager.GetString("GingerLiveSpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Ginger will replace with the code to inject
        ///
        ///// Enable to Inject/Add Java script to page
        ///
        ///// Ginger will replace with the code to inject
        ///
        ///var s = &quot;%SCRIPT%&quot; 
        ///
        ///// Something to show that we injected the script, will highligh then go down 
        ///var el = document.createElement(&apos;div&apos;),
        ///b = document.getElementsByTagName(&apos;body&apos;)[0];
        ///otherlib = false,
        ///msg = &apos;&apos;;
        ///el.style.position = &apos;fixed&apos;;
        ///el.style.height = &apos;32px&apos;;
        ///el.style.width = &apos;220px&apos;;
        ///el.style.marginLeft = &apos;-110px&apos;;
        ///el.style.top = &apos;0&apos;;
        ///el.styl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InjectJavaScript {
            get {
                return ResourceManager.GetString("InjectJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function (a, b) { &quot;object&quot; == typeof module &amp;&amp; &quot;object&quot; == typeof module.exports ? module.exports = a.document ? b(a, !0) : function (a) { if (!a.document) throw new Error(&quot;jQuery requires a window with a document&quot;); return b(a) } : b(a) }(&quot;undefined&quot; != typeof window ? window : this, function (a, b) {
        ///    var c = [], d = c.slice, e = c.concat, f = c.push, g = c.indexOf, h = {}, i = h.toString, j = h.hasOwnProperty, k = { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_min {
            get {
                return ResourceManager.GetString("jquery_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Copyright © 2014-2020 European Support Limited
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;)
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at 
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0 
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        ///See the License for the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PayLoad {
            get {
                return ResourceManager.GetString("PayLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    function h(a) { return function () { return this[a] } } function l(a) { return function () { return a } } var m = this;
        ///function aa(a){var b=typeof a;if(&quot;object&quot;==b)if(a){if(a instanceof Array)return&quot;array&quot;;if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(&quot;[object Window]&quot;==c)return&quot;object&quot;;if(&quot;[object Array]&quot;==c||&quot;number&quot;==typeof a.length&amp;&amp;&quot;undefined&quot;!=typeof a.splice&amp;&amp;&quot;undefined&quot;!=typeof a.propertyIsEnumerable&amp;&amp;!a.propertyIsEnumerable(&quot;splice&quot;))return&quot;array&quot;; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wgxpath_install {
            get {
                return ResourceManager.GetString("wgxpath_install", resourceCulture);
            }
        }
    }
}
