FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .

RUN dotnet restore

# copy everything else and build app
COPY . .
WORKDIR /app/ginger
RUN dotnet build





FROM build AS publish
WORKDIR /app/ginger
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/framework/runtime:4.8 AS runtime
WORKDIR /app
COPY --from=publish /app/ginger/out ./
ENTRYPOINT ["ginger.exe"]