name: dockerdemo

on:
  workflow_dispatch: 
    inputs:
      Version:
        type: string 
        required: true
  workflow_call:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deploy
    permissions:
      contents: read
      packages: write
    
    env:
      BUILD_CONFIGURATION: Release
      
    steps:    
# ------------------------------------------------------------------------------------------------------
# Createin version Tag & Number variables 
# ------------------------------------------------------------------------------------------------------
      -   name: Create Version Environment Variable
          id: set_version
          if: ${{github.workflow == 'CD'}} 
          run: |
              if [[ ${{github.event.inputs.revision}} != 0 ]]; then 
                  echo "Alpha Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Alpha.${{github.event.inputs.build}}.${{ github.event.inputs.revision}}" >> $GITHUB_ENV
              elif [[ ${{github.event.inputs.build}} != 0 && ${{github.event.inputs.revision}} == 0 ]]; then
                  echo "Beta Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Beta.${{ github.event.inputs.build}}" >> $GITHUB_ENV
              elif [[ ${{github.event.inputs.build}} == 0  &&  ${{github.event.inputs.revision}} == 0 ]]; then
                  echo "Official Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Official" >> $GITHUB_ENV
              fi
              echo "ginger gingertag ${{env.gingertag}}"

      -   name: Print Version Environment Variable
          if: ${{github.workflow == 'CD'}} 
          run: |
              echo "GingerTag Version: ${{ env.gingertag}}"
        

      - name: Restore static site content
        uses: actions/cache@v4
        with:
          path: ./**
          key: cache-site-linux-${{ github.run_number }}
          enableCrossOsArchive:
              true

      - name: Print File Content
        run: | 
          ls  
          echo "==============================================="
          cd Ginger/GingerRuntime
          ls           

# ------------------------------------------------------------------------------------------------------
# Log in to the Container registry - GHCR
# ------------------------------------------------------------------------------------------------------
      - name: Log in to the Container registry - GHCR
        run: | 
          cd Ginger/GingerRuntime
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
# ------------------------------------------------------------------------------------------------------
# Create GingerRuntime-jammy docker image
# ------------------------------------------------------------------------------------------------------
      - name: Building GingerRuntime docker image
        run: |
          cd Ginger/GingerRuntime
          docker build -t gingerruntime-jammy .
        
      - name: Change image tag to be pushed for GHCR
        run: |
          docker tag gingerruntime-jammy ghcr.io/ginger-automation/gingerruntime-jammy:${{ env.gingertag }}
  
# ------------------------------------------------------------------------------------------------------
# Push GingerRuntime-jammy docker image to GitHub Container Registry
# ------------------------------------------------------------------------------------------------------
      - name: Pushing GingerRuntime Image
        run: | 
          docker push ghcr.io/ginger-automation/gingerruntime-jammy:${{ env.gingertag}}


  Publish_Latest:
    name: Publish Latest
    needs: build
    runs-on: ubuntu-latest
    environment: Deploy
    permissions:
      contents: read
      packages: write
    
    env:
      BUILD_CONFIGURATION: Release
      
    steps:    
# ------------------------------------------------------------------------------------------------------
# Createin version Tag & Number variables 
# ------------------------------------------------------------------------------------------------------
      -   name: Create Version Environment Variable
          id: set_version
          if: ${{github.workflow == 'CD'}} 
          run: |
              if [[ ${{github.event.inputs.revision}} != 0 ]]; then 
                  echo "Alpha Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Alpha.${{github.event.inputs.build}}.${{ github.event.inputs.revision}}" >> $GITHUB_ENV
              elif [[ ${{github.event.inputs.build}} != 0 && ${{github.event.inputs.revision}} == 0 ]]; then
                  echo "Beta Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Beta.${{ github.event.inputs.build}}" >> $GITHUB_ENV
              elif [[ ${{github.event.inputs.build}} == 0  &&  ${{github.event.inputs.revision}} == 0 ]]; then
                  echo "Official Version"
                  echo "gingertag=20${{ github.event.inputs.major}}.${{ github.event.inputs.minor}}-Official" >> $GITHUB_ENV
              fi
              echo "ginger gingertag ${{env.gingertag}}" 
              
      -   name: Print Version Environment Variable
          if: ${{github.workflow == 'CD'}} 
          run: |
              echo "GingerNumber Version: ${{ env.gingertag}}"

# ------------------------------------------------------------------------------------------------------
# Log in to the Container registry - GHCR
# ------------------------------------------------------------------------------------------------------
      - name: Log in to the Container registry - GHCR
        run: | 
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
# ------------------------------------------------------------------------------------------------------
# Pull GingerRuntime-jammy docker image from Github Container Registry
# ------------------------------------------------------------------------------------------------------
      - name: Pull GingerRuntime docker image
        run: |
          docker pull ghcr.io/ginger-automation/gingerruntime-jammy:${{ env.gingertag}}
        
      - name: Change image tag(latest) to be pushed for GHCR
        run: |
          docker tag ghcr.io/ginger-automation/gingerruntime-jammy:${{ env.gingertag}} ghcr.io/ginger-automation/gingerruntime-jammy:latest

# ------------------------------------------------------------------------------------------------------
# Push GingerRuntime-jammy docker image to GitHub Container Registry
# ------------------------------------------------------------------------------------------------------          
      - name: Pushing GingerRuntime Image
        run: | 
          docker push ghcr.io/ginger-automation/gingerruntime-jammy:latest