name: Ginger Linux Build

on:
  # pull_request:
  #   branches: 
  #     - master
  #     - Features/Linux-Migration
  #     - Releases/*
  #     - Releases/*/*
      
  workflow_dispatch: 


jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIGURATION: Release
    
    steps:     
      - uses: actions/checkout@v3
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100'
      
    
    
      - name: 'printing file - GingerConsole.dll'
        if: success() || failure()        # run this step even if previous step failed
        run: | 
          ls -alt Ginger/GingerUtilsTest 
# ------------------------------------------------------------------------------------------------------
# start Testing 
# ------------------------------------------------------------------------------------------------------
      - name: Testing GingerUtilsTest
        run: dotnet test  Ginger/GingerUtilsTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
        
      - name: 'printing file - GingerConsole.dll'
        if: success() || failure()        # run this step even if previous step failed
        run: | 
          ls -alt Ginger/GingerUtilsTest 
      
      - name: 'Testing GingerCoreCommonTest'
        run: dotnet test  Ginger/GingerCoreCommonTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal

        # for GingerCoreNET we use run setting to limit to have one worker thread due to workspace limitation
      - name: 'Testing GingerCoreNETUnitTest'
        run: dotnet test  Ginger/GingerCoreNETUnitTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal

      - name: 'Testing GingerPluginCoreTest'
        run: dotnet test  Ginger/GingerPluginCoreTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal

      - name: 'Testing GingerConsoleTest'
        run: dotnet test  Ginger/GingerConsoleTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal

      - name: 'Testing GingerAutoPilotTest'
        run: dotnet test  Ginger/GingerAutoPilotTest --configuration ${BUILD_CONFIGURATION} --logger trx --verbosity=normal
        
        
        
# ------------------------------------------------------------------------------------------------------
# Publish GingerRuntime
# ------------------------------------------------------------------------------------------------------
      - name: 'Publish GingerRuntime'
        run: dotnet publish  Ginger/GingerRuntime -c Release
        
        
        
# ------------------------------------------------------------------------------------------------------
# Publish Test Results
# ------------------------------------------------------------------------------------------------------   
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: Ginger Linux UnitTests    # Name of the check run which will be created
          path: "**/*.trx"                # Path to test results
          reporter: dotnet-trx            # Format of test results
      
      
          
# ------------------------------------------------------------------------------------------------------
# Run Standalone CLI Test
# ------------------------------------------------------------------------------------------------------          
      - name: Run Standalone CLI Test
        if: success() || failure()        # run this step even if previous step failed
        run: |
          chmod +x CLITestsGithub.ps1
          ./CLITestsGithub.ps1
