
                if: ${{ github.event.inputs.SSLCert != 'No' }}
                uses: digicert/ssm-code-signing@v0.0.2
            
            
            
    
            -   name: Setup SSM KSP on windows latest 
                if: ${{ github.event.inputs.SSLCert != 'No' }}
                run: | 
                 curl -X GET  https://one.digicert.com/signingmanager/api-ui/v1/releases/Keylockertools-windows-x64.msi/download -H "x-api-key:[Credentials]" -o keylockertools-windows-x64.msi 
                    msiexec /i keylockertools-windows-x64.msi /quiet /qn 
                    smksp_registrar.exe list 
                    smctl.exe keypair ls 
                    C:\Windows\System32\certutil.exe -csp "DigiCert Signing Manager KSP" -key -user 
                shell: cmd 
                
             # uses: nadeemjazmawe/Sign-action-signtool.exe@v0.1
            #-   name: Windows signtool.exe code sign action
              #  uses: skymatic/code-sign-action@v3.0.0
            
                
            
           # -   name: Find Signtool
            #    run: |
             #       nadeemjazmawe/Sign-action-signtool.exe@v0.1
            #    shell: cmd
              
            -  name: Certificates Sync     
               if: ${{ github.event.inputs.SSLCert != 'No' }}
               run: |
                  smctl windows certsync
               shell: cmd
                    
            - name: Create Signed Directory for dll 
              if: ${{ github.event.inputs.SSLCert != 'No' }}
              run: |
                 mkdir -p D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist
              shell: cmd
              
            -   name: Signing using Signtool dll
                if: ${{ github.event.inputs.SSLCert != 'No' }}
                #runs-on: windows-latest
                #folder: 'D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\'
                #recursive: true
                 #if {% ${{ folder }}='Ginger'%}
                run: | 
                 dir "D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\"
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerCore.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerCore.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\Ginger.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\Ginger.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\Ginger.ExecuterService.Contracts.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\Ginger.ExecuterService.Contracts.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\Ginger.External.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\Ginger.External.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerAutoPilot.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerAutoPilot.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerControls.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerControls.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerCoreNET.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerCoreNET.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerCoreCommon.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerCoreCommon.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerExternal.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerExternal.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerHelper.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerHelper.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerHbaseFilter.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerHbaseFilter.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerPluginCore.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerPluginCore.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerPlugIns.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerPlugIns.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerUtils.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerUtils.dll
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\Ginger.exe D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\Ginger.exe
                 copy D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\GingerWin64OsSupport.dll D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerWin64OsSupport.dll
                 
                 signtool.exe sign /sha1 b04acd961a24c99503145b62ed77ebe7e5b0da66 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /v D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\Ginger.dll
                 signtool.exe sign /sha1 b04acd961a24c99503145b62ed77ebe7e5b0da66 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /v D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\Ginger.ExecuterService.Contracts.dll
                 signtool.exe sign /sha1 b04acd961a24c99503145b62ed77ebe7e5b0da66 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /v D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\Ginger.External.dll
                 signtool.exe sign /sha1 b04acd961a24c99503145b62ed77ebe7e5b0da66 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /v D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerAutoPilot.dll
                 signtool.exe sign /sha1 b04acd961a24c99503145b62ed77ebe7e5b0da66 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /v D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerControls.dll
                 signtool.exe sign /sha1 b04acd961a24c99503145b62ed77ebe7e5b0da66 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /v D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerCore.dll
                 signtool.exe sign /sha1 b04acd961a24c99503145b62ed77ebe7e5b0da66 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /v D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerCoreNET.dll
                 signtool.exe sign /sha1 b04acd961a24c99503145b62ed77ebe7e5b0da66 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /v D:\a\Ginger\Ginger\Ginger\Ginger\bin\Release\net10.0-windows10.0.17763.0\dist\GingerCoreCommon.dll
