name: Release

on:
    workflow_dispatch: 
    
    workflow_call:

jobs:
                    

    Linux:
        name: Create GingerRuntime
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                name: ginger-artifact
 
            -   uses: sibiraj-s/action-archiver@v1
                with:
                  path: './Ginger/GingerRuntime/bin/Release/net6.0/linux-x64'
                  format: tar
                  gzip: true
                  output: GingerRuntime.tar.gz
                  
            -   name: Upload GingerRuntime
                uses: actions/upload-artifact@v3
                with:
                  name: GingerRuntime
                  path: ./GingerRuntime.tar.gz
                  
          
    Windows:
        name: Windows Installer
        runs-on: windows-latest     
        steps:
            -   name: Download Artifacts
                uses: actions/download-artifact@v3
                with:
                  name: ginger-artifact         
                     
            -   uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
                with: 
                    filepath: './Ginger/GingerInstallerScriptGithub.iss'
                    
            -   name: Upload Windows Installer
                uses: actions/upload-artifact@v3
                with:
                  name: WindowsInstaller
                  path: D:/a/Installers
                    
